version: "3.9"

services:
  db:
    image: postgres:15
    container_name: energy-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: energy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/db/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql

  api:
    build: .
    container_name: energy-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/energy
    depends_on:
      - db

volumes:
  pgdata:
